services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.prd
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=desenv
    volumes:
      - ./cnpjbrasil/src:/app/src
      - ./.m2:/root/.m2
      # - ./dbwallet:/app/dbwallet:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

#   db:
#     image: postgres
#     volumes:
#       # - ./data/db:/var/lib/postgresql/data
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
# volumes:
#   postgres_data: